framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - vendor/sumocoders/framework-core-bundle/assets-public/
            - vendor/twbs/bootstrap-icons/font/
        missing_import_mode: strict
        excluded_patterns:
            - '**/assets/styles/**/_*.scss'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
